#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  Aug 06, 2026 03:37:14 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Relative
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 208x300+640+182
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "SP"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Baudrate:" \
        -underline -1 -width 79 -wraplength 0 
    vTcl:DefineAlias "$top.lab50" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Port:" \
        -underline -1 -width 47 -wraplength 0 
    vTcl:DefineAlias "$top.lab51" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but56" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -compound left -default disabled \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 12" \
        -foreground #000000 -height 36 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -justify center -padx 1 \
        -pady 1 -relief raised -repeatdelay 0 -repeatinterval 0 -state normal \
        -text "Connect" -underline -1 -width 77 -wraplength 0 
    vTcl:DefineAlias "$top.but56" "Button1" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent49" \
        -background #d9d9d9 -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {Courier New} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 164 
    vTcl:DefineAlias "$top.ent49" "BaudTextBox" vTcl:WidgetProc "Toplevel1" 1
    menubutton "$top.men57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 1 -direction below \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -indicatoron 1 \
        -justify center -menu $top.men57.m -padx 5 -pady 4 -relief sunken -compound left \
        -state normal -takefocus 0 -text "Select Port" -underline -1 \
        -width 166 -wraplength 0 
    vTcl:DefineAlias "$top.men57" "Menubutton1" vTcl:WidgetProc "Toplevel1" 1
# add aa target = .top1.men57.m, basename = $top.men57.m
    menu "$top.men57.m" \
        -activebackground SystemHighlight -activeborderwidth 1 \
        -activeforeground SystemHighlightText -background #d9d9d9 \
        -borderwidth 1 -cursor arrow -disabledforeground #a3a3a3 \
        -font "TkMenuFont" -foreground #000000 -relief flat \
        -selectcolor SystemMenuText -takefocus 0 -tearoff 0 -type normal 
# add first menu widget
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.lab50
    place $top.lab50 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.033 -width 0 -relwidth 0.38 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab51
    place $top.lab51 \
        -in $top -x 0 -relx 0.096 -y 0 -rely 0.233 -width 0 -relwidth 0.226 \
        -height 0 -relheight 0.097 -anchor nw -bordermode ignore 
# add p1 basename = $top.but56
    place $top.but56 \
        -in $top -x 0 -relx 0.288 -y 0 -rely 0.767 -width 77 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.ent49
    place $top.ent49 \
        -in $top -x 0 -relx 0.096 -y 0 -rely 0.133 -width 164 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.men57
    place $top.men57 \
        -in $top -x 0 -relx 0.096 -y 0 -rely 0.333 -width 0 -relwidth 0.798 \
        -height 0 -relheight 0.083 -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

