#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Aug 06, 2026 03:37:17 PM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import window_support

from serial_tools import list_ports
import Config

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("208x300+640+182")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("SP")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.config = Config

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.067, rely=0.033, height=34, width=79)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Baudrate:''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.096, rely=0.233, height=29, width=47)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 12")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''Port:''')

        self.BaudTextBox = tk.Entry(self.top)
        self.BaudTextBox.place(relx=0.096, rely=0.133, height=20, relwidth=0.788)

        self.BaudTextBox.configure(background="#d9d9d9")
        self.BaudTextBox.configure(disabledforeground="#a3a3a3")
        self.BaudTextBox.configure(exportselection="0")
        self.BaudTextBox.configure(font="-family {Courier New} -size 14")
        self.BaudTextBox.configure(foreground="#000000")
        self.BaudTextBox.configure(highlightbackground="#d9d9d9")
        self.BaudTextBox.configure(highlightcolor="#000000")
        self.BaudTextBox.configure(insertbackground="#000000")
        self.BaudTextBox.configure(selectbackground="#d9d9d9")
        self.BaudTextBox.configure(selectforeground="black")

        self.Button1 = tk.Button(self.top, command=lambda: self.connect())
        self.Button1.place(relx=0.288, rely=0.767, height=36, width=77)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 12")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Connect''')

        self.Menubutton1 = tk.Menubutton(self.top)
        self.Menubutton1.place(relx=0.096, rely=0.333, relheight=0.083
                               , relwidth=0.798)
        self.men57_m = tk.Menu(self.Menubutton1, tearoff=0, background=_bgcolor)

        lista = list_ports()
        if not lista:
            self.men57_m.add_command(label="No hay puertos disponibles", state="disabled")
        else:
            for item in lista:
                self.men57_m.add_command(
                    label=item,
                    command=lambda p=item: self.select_port(p)
                )

        self.Menubutton1.configure(activebackground="#d9d9d9")
        self.Menubutton1.configure(activeforeground="black")
        self.Menubutton1.configure(anchor='w')
        self.Menubutton1.configure(background="#d9d9d9")
        self.Menubutton1.configure(disabledforeground="#a3a3a3")
        self.Menubutton1.configure(font="-family {Segoe UI} -size 12")
        self.Menubutton1.configure(foreground="#000000")
        self.Menubutton1.configure(highlightbackground="#d9d9d9")
        self.Menubutton1.configure(highlightcolor="#000000")
        self.Menubutton1.configure(indicatoron="1")
        self.Menubutton1.configure(menu=self.men57_m)
        self.Menubutton1.configure(padx="5")
        self.Menubutton1.configure(pady="4")
        self.Menubutton1.configure(relief="sunken")
        self.Menubutton1.configure(compound='left')

    def select_port(self, port):
        self.config.Config.set_port(self, port)
        self.Menubutton1.configure(text=port)

    def connect(self):
        self.config.Config.set_baud_rate(self, self.BaudTextBox.get())
        # TODO: send config object to the plotter
        self.top.destroy()


def start_up():
    window_support.main()

if __name__ == '__main__':
    window_support.main()




