#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Aug 10, 2026 12:24:02 AM CEST  platform: Windows NT

import sys
import tkinter as tk
from tkinter import messagebox
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

from DataWindow import DataWindow

_location = os.path.dirname(__file__)

import window_support

from serial_tools import list_ports, SerialReader
from Config import Config

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40'


def _valid_integer(value):
    try:
        int(value)
        return True
    except ValueError:
        return False


class Toplevel1:
    def __init__(self, top=None):
        """
        This class configures and populates the toplevel window.
        top is the toplevel containing window.
        """

        top.geometry("208x300+640+182")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("SP")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.config = Config()
        self.serial_reader = None

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.096, rely=0.0, height=34, width=79)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Baudrate:''')

        self.BaudTextBox = tk.Entry(self.top)
        self.BaudTextBox.place(relx=0.096, rely=0.133, height=20, relwidth=0.788)

        self.BaudTextBox.configure(background="#d9d9d9")
        self.BaudTextBox.configure(disabledforeground="#a3a3a3")
        self.BaudTextBox.configure(exportselection="0")
        self.BaudTextBox.configure(font="-family {Courier New} -size 14")
        self.BaudTextBox.configure(foreground="#000000")
        self.BaudTextBox.configure(highlightbackground="#d9d9d9")
        self.BaudTextBox.configure(highlightcolor="#000000")
        self.BaudTextBox.configure(insertbackground="#000000")
        self.BaudTextBox.configure(selectbackground="#d9d9d9")
        self.BaudTextBox.configure(selectforeground="black")

        self.Menubutton1 = tk.Menubutton(self.top)
        self.Menubutton1.place(relx=0.096, rely=0.3, relheight=0.083
                , relwidth=0.798)
        self.men57_m = tk.Menu(self.Menubutton1,tearoff=0,background=_bgcolor)

        lista = list_ports()
        if not lista:
            self.men57_m.add_command(label="No hay puertos disponibles", state="disabled")
        else:
            for item in lista:
                self.men57_m.add_command(
                    label=item,
                    command=lambda p=item: self.select_port(p)
                )

        self.Menubutton1.configure(activebackground="#d9d9d9")
        self.Menubutton1.configure(activeforeground="black")
        self.Menubutton1.configure(anchor='w')
        self.Menubutton1.configure(background="#d9d9d9")
        self.Menubutton1.configure(disabledforeground="#a3a3a3")
        self.Menubutton1.configure(font="-family {Segoe UI} -size 12")
        self.Menubutton1.configure(foreground="#000000")
        self.Menubutton1.configure(highlightbackground="#d9d9d9")
        self.Menubutton1.configure(highlightcolor="#000000")
        self.Menubutton1.configure(indicatoron="1")
        self.Menubutton1.configure(menu=self.men57_m)
        self.Menubutton1.configure(padx="5")
        self.Menubutton1.configure(pady="4")
        self.Menubutton1.configure(relief="sunken")
        self.Menubutton1.configure(compound='left')
        self.Menubutton1.configure(text='''Select Port''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.096, rely=0.2, height=29, width=47)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 12")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''Port:''')

        self.SampleTimeLabel = tk.Label(self.top)
        self.SampleTimeLabel.place(relx=0.096, rely=0.567, height=21, width=114)
        self.SampleTimeLabel.configure(activebackground="#d9d9d9")
        self.SampleTimeLabel.configure(activeforeground="black")
        self.SampleTimeLabel.configure(anchor='w')
        self.SampleTimeLabel.configure(background="#d9d9d9")
        self.SampleTimeLabel.configure(compound='left')
        self.SampleTimeLabel.configure(disabledforeground="#a3a3a3")
        self.SampleTimeLabel.configure(font="-family {Segoe UI} -size 12")
        self.SampleTimeLabel.configure(foreground="#000000")
        self.SampleTimeLabel.configure(highlightbackground="#d9d9d9")
        self.SampleTimeLabel.configure(highlightcolor="#000000")
        self.SampleTimeLabel.configure(text='''Sample Time:''')

        self.RegexEntry = tk.Entry(self.top)
        self.RegexEntry.place(relx=0.096, rely=0.5, height=20, relwidth=0.788)
        self.RegexEntry.configure(background="#d9d9d9")
        self.RegexEntry.configure(disabledforeground="#a3a3a3")
        self.RegexEntry.configure(exportselection="0")
        self.RegexEntry.configure(font="-family {Courier New} -size 12")
        self.RegexEntry.configure(foreground="#000000")
        self.RegexEntry.configure(highlightbackground="#d9d9d9")
        self.RegexEntry.configure(highlightcolor="#000000")
        self.RegexEntry.configure(insertbackground="#000000")
        self.RegexEntry.configure(selectbackground="#d9d9d9")
        self.RegexEntry.configure(selectforeground="black")

        self.RegexLabel = tk.Label(self.top)
        self.RegexLabel.place(relx=0.096, rely=0.4, height=21, width=64)
        self.RegexLabel.configure(activebackground="#d9d9d9")
        self.RegexLabel.configure(activeforeground="black")
        self.RegexLabel.configure(anchor='w')
        self.RegexLabel.configure(background="#d9d9d9")
        self.RegexLabel.configure(compound='left')
        self.RegexLabel.configure(disabledforeground="#a3a3a3")
        self.RegexLabel.configure(font="-family {Segoe UI} -size 12")
        self.RegexLabel.configure(foreground="#000000")
        self.RegexLabel.configure(highlightbackground="#d9d9d9")
        self.RegexLabel.configure(highlightcolor="#000000")
        self.RegexLabel.configure(text='''Regex:''')

        self.ConnectBtn = tk.Button(self.top, command=lambda: self.connect())
        self.ConnectBtn.place(relx=0.288, rely=0.8, height=36, width=77)
        self.ConnectBtn.configure(activebackground="#d9d9d9")
        self.ConnectBtn.configure(activeforeground="black")
        self.ConnectBtn.configure(background="#d9d9d9")
        self.ConnectBtn.configure(compound='left')
        self.ConnectBtn.configure(disabledforeground="#a3a3a3")
        self.ConnectBtn.configure(font="-family {Segoe UI} -size 12")
        self.ConnectBtn.configure(foreground="#000000")
        self.ConnectBtn.configure(highlightbackground="#d9d9d9")
        self.ConnectBtn.configure(highlightcolor="#000000")
        self.ConnectBtn.configure(text='''Connect''')

        self.SampleTimeEntry = tk.Spinbox(self.top, from_=-1.0, to=100.0)
        self.SampleTimeEntry.place(relx=0.096, rely=0.667, relheight=0.063
                , relwidth=0.793)
        self.SampleTimeEntry.configure(activebackground="#d9d9d9")
        self.SampleTimeEntry.configure(background="white")
        self.SampleTimeEntry.configure(disabledforeground="#a3a3a3")
        self.SampleTimeEntry.configure(exportselection="0")
        self.SampleTimeEntry.configure(font="-family {Segoe UI} -size 12")
        self.SampleTimeEntry.configure(foreground="#000000")
        self.SampleTimeEntry.configure(highlightbackground="black")
        self.SampleTimeEntry.configure(highlightcolor="#000000")
        self.SampleTimeEntry.configure(insertbackground="#000000")
        self.SampleTimeEntry.configure(selectbackground="#d9d9d9")
        self.SampleTimeEntry.configure(selectforeground="black")

        self.top.protocol("WM_DELETE_WINDOW", lambda: self._on_close())

    def select_port(self, port):
        self.config.set_port(port)
        self.Menubutton1.configure(text=port)

    def validate_data(self):
        is_valid = True

        if not _valid_integer(self.BaudTextBox.get()) or not _valid_integer(self.SampleTimeEntry.get()):
            is_valid = False

        return is_valid

    def connect(self):
        if not self.validate_data():
            print("Revisa los datos, alguno debe estar incorrecto.")
            messagebox.showerror("Error", "Revisa los datos, parece haber datos incorrectos.")
            return

        self.config.set_regex(self.RegexEntry.get())
        self.config.set_baud_rate(self.BaudTextBox.get())
        self.config.set_sample_time(self.SampleTimeEntry.get())
        print(self.config.__str__())

        try:
            self.serial_reader = SerialReader(
                self.config.get_port(),
                self.config.get_baud_rate()
            )
            self.serial_reader.start()
        except Exception as e:
            messagebox.showerror("Error de conexion", str(e))
            return

        self.data_window = DataWindow(self.top, self.serial_reader)
        self.top.withdraw()

    def _on_close(self):
        if self.serial_reader:
            self.serial_reader.stop()
        self.top.destroy()

def start_up():
    window_support.main()

if __name__ == '__main__':
    window_support.main()




